"""Built-in theme palettes and definitions for Rudra."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


@dataclass
class ThemePalette:
    name: str
    label: str
    description: str
    author: str = "Rudra Community"
    primary: str = "cyan"
    secondary: str = "blue"
    accent: str = "magenta"
    success: str = "green"
    warning: str = "yellow"
    error: str = "red"
    info: str = "cyan"
    dim: str = "slate"
    panel_border: str = "cyan"
    table_header: str = "bold cyan"
    banner_gradient: tuple[str, str] = ("cyan", "blue")
    prompt_char: str = "⚡"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


BUILTIN_THEMES: dict[str, ThemePalette] = {
    "default": ThemePalette(
        name="default",
        label="Rudra Classic",
        description="Electric cyan and deep azure blue with clean modern borders.",
        primary="cyan",
        secondary="blue",
        accent="magenta",
        success="green",
        warning="yellow",
        error="red",
        info="cyan",
        dim="dim",
        panel_border="cyan",
        table_header="bold cyan",
        banner_gradient=("cyan", "blue"),
        prompt_char="⚡",
    ),
    "cyberpunk": ThemePalette(
        name="cyberpunk",
        label="Night City Cyberpunk",
        description="High-contrast neon yellow, hot magenta, electric cyan and dark chrome.",
        primary="bright_yellow",
        secondary="bright_magenta",
        accent="bright_cyan",
        success="bright_green",
        warning="yellow",
        error="bright_red",
        info="bright_cyan",
        dim="dim",
        panel_border="bright_magenta",
        table_header="bold bright_yellow",
        banner_gradient=("bright_yellow", "bright_magenta"),
        prompt_char="☣",
    ),
    "dracula": ThemePalette(
        name="dracula",
        label="Dracula Vampire",
        description="Gothic purple, hot pink, soft green, and Dracula cyan.",
        primary="magenta",
        secondary="purple",
        accent="cyan",
        success="green",
        warning="yellow",
        error="red",
        info="cyan",
        dim="dim white",
        panel_border="purple",
        table_header="bold magenta",
        banner_gradient=("purple", "magenta"),
        prompt_char="🦇",
    ),
    "catppuccin": ThemePalette(
        name="catppuccin",
        label="Catppuccin Mocha",
        description="Warm pastel lavender, soothing sapphire blue, rosewater, and peach.",
        primary="bright_magenta",
        secondary="bright_blue",
        accent="bright_cyan",
        success="green",
        warning="bright_yellow",
        error="bright_red",
        info="bright_blue",
        dim="dim",
        panel_border="bright_blue",
        table_header="bold bright_magenta",
        banner_gradient=("bright_magenta", "bright_blue"),
        prompt_char="🌸",
    ),
    "nord": ThemePalette(
        name="nord",
        label="Nordic Frost",
        description="Arctic blue, glacier frost, polar night slate, and clean snow white.",
        primary="bright_cyan",
        secondary="blue",
        accent="cyan",
        success="green",
        warning="yellow",
        error="red",
        info="bright_cyan",
        dim="dim",
        panel_border="bright_cyan",
        table_header="bold bright_cyan",
        banner_gradient=("bright_cyan", "blue"),
        prompt_char="❄",
    ),
    "matrix": ThemePalette(
        name="matrix",
        label="Matrix Terminal",
        description="Hacker phosphor green, emerald matrix code, and terminal black.",
        primary="bright_green",
        secondary="green",
        accent="spring_green2",
        success="bright_green",
        warning="yellow",
        error="red",
        info="green",
        dim="dim green",
        panel_border="green",
        table_header="bold bright_green",
        banner_gradient=("bright_green", "green"),
        prompt_char="λ",
    ),
    "tokyo-night": ThemePalette(
        name="tokyo-night",
        label="Tokyo Night",
        description="Deep indigo night, electric neon blue, vibrant purple, and sunset orange.",
        primary="blue",
        secondary="bright_magenta",
        accent="bright_cyan",
        success="green",
        warning="yellow",
        error="red",
        info="blue",
        dim="dim",
        panel_border="blue",
        table_header="bold bright_magenta",
        banner_gradient=("blue", "bright_magenta"),
        prompt_char="🗼",
    ),
    "gruvbox": ThemePalette(
        name="gruvbox",
        label="Gruvbox Retro",
        description="Warm retro autumn colors, earthy amber, olive green, and rust red.",
        primary="yellow",
        secondary="bright_yellow",
        accent="dark_orange",
        success="green",
        warning="yellow",
        error="red",
        info="yellow",
        dim="dim yellow",
        panel_border="yellow",
        table_header="bold yellow",
        banner_gradient=("yellow", "dark_orange"),
        prompt_char="☕",
    ),
    "synthwave": ThemePalette(
        name="synthwave",
        label="Synthwave '84",
        description="Retro 80s outrun sunset, laser hot pink, neon orange, and grid purple.",
        primary="bright_magenta",
        secondary="bright_yellow",
        accent="bright_cyan",
        success="bright_green",
        warning="bright_yellow",
        error="bright_red",
        info="bright_cyan",
        dim="dim",
        panel_border="bright_magenta",
        table_header="bold bright_yellow",
        banner_gradient=("bright_magenta", "bright_yellow"),
        prompt_char="🕶",
    ),
    "monochrome": ThemePalette(
        name="monochrome",
        label="Minimalist Monochrome",
        description="Clean high-contrast pure white, silver borders, and subtle minimalist text.",
        primary="bold white",
        secondary="white",
        accent="bright_white",
        success="white",
        warning="dim white",
        error="bold red",
        info="white",
        dim="dim",
        panel_border="white",
        table_header="bold white",
        banner_gradient=("white", "white"),
        prompt_char="❯",
    ),
    "rose-pine": ThemePalette(
        name="rose-pine",
        label="Rosé Pine",
        description="All natural pine, fragrant rose, soft gold, and muted iris tones.",
        primary="bright_magenta",
        secondary="bright_cyan",
        accent="bright_yellow",
        success="green",
        warning="yellow",
        error="bright_red",
        info="bright_cyan",
        dim="dim",
        panel_border="bright_magenta",
        table_header="bold bright_magenta",
        banner_gradient=("bright_magenta", "bright_cyan"),
        prompt_char="🌹",
    ),
    "one-dark": ThemePalette(
        name="one-dark",
        label="One Dark Pro",
        description="Atom iconic dark theme — chalky blue, vibrant green, soft red, and violet.",
        primary="bright_blue",
        secondary="bright_magenta",
        accent="bright_cyan",
        success="bright_green",
        warning="bright_yellow",
        error="bright_red",
        info="bright_cyan",
        dim="dim",
        panel_border="bright_blue",
        table_header="bold bright_blue",
        banner_gradient=("bright_blue", "bright_magenta"),
        prompt_char="⚛",
    ),
    "monokai": ThemePalette(
        name="monokai",
        label="Monokai Pro",
        description="Sublime Text classic — vivid lime green, electric orange, hot pink, and sky blue.",
        primary="bright_yellow",
        secondary="bright_green",
        accent="bright_magenta",
        success="bright_green",
        warning="bright_yellow",
        error="bright_red",
        info="bright_cyan",
        dim="dim",
        panel_border="bright_yellow",
        table_header="bold bright_yellow",
        banner_gradient=("bright_yellow", "bright_green"),
        prompt_char="👾",
    ),
    "solarized": ThemePalette(
        name="solarized",
        label="Solarized Dark",
        description="Precision colors engineered for readability — cyan, blue, magenta, and green.",
        primary="cyan",
        secondary="bright_cyan",
        accent="blue",
        success="green",
        warning="yellow",
        error="red",
        info="cyan",
        dim="dim cyan",
        panel_border="cyan",
        table_header="bold cyan",
        banner_gradient=("cyan", "blue"),
        prompt_char="☀",
    ),
}

